### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by sabirali007** [ccapndave/cordova-image-audio-merger#1]
when i call this function in android 
window.imageaudiomerger.merge('img/thumb .png', 'img/2barf1.wav', function(res){console.log(res)}, function(error){console.log(error)}

it return Class not found in error call back function
please help me on this issue
Thanks

**Comment by ccapndave** [comment]
Its iOS only I'm afraid.  If you want to write an Android bit for it that would be great!

**Comment by sabirali007** [comment]
Thanks
